---
name: Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Codespell
        uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630
        with:
          skip: '*.js'
